version: "3.8"

networks:
  mynotes:
    driver: bridge

volumes:
  mysql_db_volume:
    driver: local
  postgres_db_volume:
    driver: local

services:
  noteapp:
    image: "php:8.1-apache"
    build:
      context: .docker
    restart: always
    ports:
      - "81:80"
    volumes:
      - .:/var/www/html
    networks:
      - mynotes

  mysql_db:
    image: "mysql:8"
    restart: always
    ports:
      - "33061:3306"
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - "mysql_db_volume:/var/lib/mysql"
    networks:
      - mynotes

  pgsql:
    restart: always
    image: sameersbn/postgresql:15-20230628
    ports:
      - "5432:5432"
    networks:
      - mynotes

    environment:
      - DEBUG=false
      - DB_USER=root
      - DB_PASS=secret
      - DB_NAME=pgdb
      - DB_TEMPLATE=
      - DB_EXTENSION=
      - REPLICATION_MODE=
      - REPLICATION_USER=repl
      - REPLICATION_PASS=secret
      - REPLICATION_SSLMODE=
    volumes:
      - "postgres_db_volume:/usr/local/pgsql"

  adminer:
    image: adminer
    restart: always
    networks:
      - mynotes
    ports:
      - 8080:8080