<?php

namespace App\Controllers;

use Core\Controller;

class UsersController extends Controller
{

    public function index()
    {

    }

    public function show($id)
    {

    }

    public function edit($id)
    {

    }

    public function before(string $action, array $params = []): bool
    {
//        if ($action === 'show' && $user != 'admin') {
//            return false;
//        }
        return parent::before($action, $params); // TODO: Change the autogenerated stub
    }
}